server:
  port: 9090
  error:
    include-binding-errors: always
    include-message: always
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demoDb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/demoDb
      username: root
      password: root
      pool-size: 20

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

flyway:
  url: jdbc:mysql://localhost:3306/demoDb
  user: root
  password: root